apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# set this namespace on all resources
namespace: syncthing

# https://truecharts.org/charts/stable/syncthing/
# https://github.com/trueforge-org/truecharts/tree/master/charts/stable/syncthing
helmcharts:
  - name: syncthing
    repo: oci://tccr.io/truecharts
    version: 22.1.4
    releaseName: syncthing
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - pvc-wunderhort_programming.yaml
  - pv-wunderhort_programming.yaml
