# the truecharts people seem to derive most of their resources from
# a common chart that gets pulled in as a dependency 
# makes stuff harder to read (hello, bitnami!)
# but i am sure there are some upsides to that too (i hope)
# Here are some places to look if you want to engross yourself in their ideas
# https://truecharts.org/common/
# https://truecharts.org/common/persistence/
# https://truecharts.org/charts/stable/syncthing
# https://github.com/trueforge-org/truecharts/tree/master/charts/library/common
# https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
# https://github.com/trueforge-org/truecharts/blob/master/charts/stable/syncthing/values.yaml


resources:
  limits:
    cpu: 4000m
    memory: 16000Mi
  requests:
    cpu: 1000m
    memory: 500Mi

global:
  storageClass: cephfs

# in case we want to force overwrite permissions
#workload:
#  main:
#    podSpec:
#      securityContext:
#        fsGroupChangePolicy: Always

# Not necessary because we squash all UIDs on the relevant NFS shares
#securityContext:
# # -- Container security context for all containers
# # Can be overruled per container
# container:
#   runAsUser: 1000
#   runAsGroup: 1000


service:
  main:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.14.4
  listeners:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.14.4
  listeners-udp:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.14.4
  discovery:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.14.4


persistence:
  data:
    enabled: true
    type: pvc
    mountPath: "/var/syncthing"
    retain: true
    size: 100Gi
    storageClass: cephfs
    accessModes:
      - ReadWriteMany
  syncthing-wunderhort-programming-static:
    type: pvc
    existingClaim: syncthing-wunderhort-programming-static
    mountPath: /wunderhort/programming
    enabled: true
  # disable default volume
  config:
    enabled: false
  # the truecharts people want to eat up to 1.5G of RAM for various dirs each
  # see https://github.com/trueforge-org/truecharts/blob/v2.0.0/charts/library/common/values.yaml#L261
  # seems like a waste, so let's not do that and use regular disk-backed emptydirs
  shared:
    enabled: true
    type: emptyDir
    mountPath: /shared
    medium: ""
    targetSelectAll: true
  varlogs:
    enabled: true
    type: emptyDir
    mountPath: /var/logs
    medium: ""
    targetSelectAll: true
  varrun:
    enabled: true
    type: emptyDir
    mountPath: /var/run
    medium: ""
    targetSelectAll: true
  tmp:
    enabled: true
    type: emptyDir
    mountPath: /tmp
    medium: ""
    targetSelectAll: true
  devshm:
    enabled: true
    type: emptyDir
    mountPath: /dev/shm
    medium: ""
    targetSelectAll: true
